/*
 * This file is generated by jOOQ.
 */
package house.greysap.shardpay.entity;


import house.greysap.shardpay.entity.tables.Payment;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PAYMENT_PKEY = Indexes0.PAYMENT_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PAYMENT_PKEY = Internal.createIndex("payment_pkey", Payment.PAYMENT, new OrderField[] { Payment.PAYMENT.PAYER, Payment.PAYMENT.PAYMENT_ID }, true);
    }
}
